"""export_tracks.py - one OGG per music track and ambience bed.

The eleven bundles in `assets/audio/bundles/` are what the game imports, and
nothing here changes that: this script does not render, does not repack, and
does not touch `build.py`, the manifest or `SoundSprites.luau`. It READS the
manifest, slices each member back out of the bundle it was packed into, and
writes it to `assets/audio/tracks/<key>.ogg` for auditioning - or for anyone
who would rather do 47 uploads than 11.

    python3 assets/audio_gen/export_tracks.py            # music + ambience
    python3 assets/audio_gen/export_tracks.py --sfx      # + the 17 cue sheets
    python3 assets/audio_gen/export_tracks.py --only island_ice

Run it AFTER `build.py`. A slice is sample-exact: the packer's offsets are
what `SoundSprites` seeks to, so a per-track file and the region inside its
bundle are the same audio, bit for bit, before the Vorbis re-encode.
"""

import argparse
import json
import os
import sys

import numpy as np
import soundfile as sf

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import synth as S  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(HERE))
BUNDLES = os.path.join(ROOT, "assets", "audio", "bundles")
MANIFEST = os.path.join(ROOT, "assets", "audio", "manifest.json")
OUT_DIR = os.path.join(ROOT, "assets", "audio", "tracks")

README = """\
assets/audio/tracks/ - one file per track. NOT what the game imports.

The 11 files in assets/audio/bundles/ are what the game imports
(SoundSprites indexes into them). These per-track files are for auditioning
or for importing individually if you prefer 47 uploads over 11 - if you
import per-track, the lane owner must regenerate SoundSprites in per-file
mode.

Generated by `python3 assets/audio_gen/export_tracks.py` from
assets/audio/manifest.json; re-run it after any build. Do not hand-edit.
"""


def _members(manifest, want_sfx):
    """[(key, bundle_file, start_s, length_s)] for everything to export."""
    # manifest["bundles"] is {bundle_name: {file, members: [{name, start,
    # length}], ...}} - the same rows SoundSprites is generated from, so a
    # slice here lands exactly where the client would seek.
    out = []
    for base, b in sorted(manifest.get("bundles", {}).items()):
        if not want_sfx and base.startswith("audio_sfx"):
            continue
        for m in b.get("members", []):
            key = m.get("name")
            start = float(m.get("start", 0.0))
            length = float(m.get("length", 0.0))
            if key and length > 0:
                out.append((key, base, start, length))
    return sorted(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--sfx", action="store_true",
                    help="also export the 17 cue sheets (mono, long)")
    ap.add_argument("--only", default=None, help="export just this key")
    ap.add_argument("--out", default=OUT_DIR)
    args = ap.parse_args(argv)

    if not os.path.exists(MANIFEST):
        sys.stderr.write("no manifest at %s - run build.py first\n" % MANIFEST)
        return 1
    with open(MANIFEST) as fh:
        manifest = json.load(fh)

    members = _members(manifest, args.sfx)
    if args.only:
        members = [m for m in members if m[0] == args.only]
        if not members:
            sys.stderr.write("no member named %r in the manifest\n" % args.only)
            return 1
    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, "README.txt"), "w") as fh:
        fh.write(README)

    cache, total = {}, 0.0
    for (key, base, start, length) in members:
        path = os.path.join(BUNDLES, base + ".ogg")
        if base not in cache:
            if not os.path.exists(path):
                sys.stderr.write("missing bundle %s\n" % path)
                return 1
            cache[base] = sf.read(path, dtype="float64", always_2d=True)[0]
        audio = cache[base]
        i0, i1 = S.n(start), S.n(start + length)
        seg = np.ascontiguousarray(audio[i0:min(i1, len(audio))])
        stereo = seg.shape[1] > 1
        S.write_ogg(os.path.join(args.out, key + ".ogg"),
                    seg if stereo else seg[:, 0], stereo=stereo)
        total += length
        print("  %-26s %8.3f s  from %s @ %8.3f" % (key, length, base, start))
    print("\n%d files in %s  (%.1f min)  - the 11 bundles are still what the "
          "game imports" % (len(members), args.out, total / 60.0))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
