#!/usr/bin/env python3
"""Regenerate `src/Shared/Config/RimefangFloe.luau` from `assets/rimefang_floe.json`.

WHY THIS EXISTS (2026-09-12). The Rimefang fight sinks and refreezes the floor
it is played on, and a Roblox mesh cannot change at runtime - so the Floe v3
floor is not one object any more, it is 43 separate `RimefangArena_ShardNN`
meshes the server toggles. To toggle them it has to KNOW them: where each one
is, which ring it sits in, which shards touch it, and which four are the thin
ice. That is a forty-three row table of measurements taken off a Blender
polygon partition, and there is exactly one honest way to carry it into Luau.

Not by hand. This repo's own history is the argument: the islet half of
`WorldService.MESH_COLOR` was hand-kept and shipped 33 rows short with every
gate green, because nothing in stylua/selene/rojo/check_content knows that a
name in a Blender script needs a matching row in a Luau table. Absence is only
loud when something is looking.

So `assets/arena_gen.py` writes `assets/rimefang_floe.json` as it builds the
floe - the one place that has seen the finished outlines - and this turns that
into the module. The chain is: re-export the arena, re-run this, commit both.

USAGE:

    python3 tools/gen_rimefang_floe.py            # rewrite the module
    python3 tools/gen_rimefang_floe.py --check    # exit 1 if it is stale

`--check` is the gate, and it mirrors `tools/gen_mesh_colors.py`'s: it writes
nothing, so it is cheap enough to run on every pass, and it fails LOUDLY when
the Luau table and the json disagree. The failure it is built for is the one
that costs an afternoon - someone re-exports the arena with a different seed,
the shard numbering shifts by one, and the server sinks the wrong piece of
floor with no error anywhere.
"""

import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "assets", "rimefang_floe.json")
OUT = os.path.join(ROOT, "src", "Shared", "Config", "RimefangFloe.luau")
STYLUA = os.path.join(os.path.expanduser("~"), ".aftman", "bin", "stylua")

HEADER = '''--!strict
-- RimefangFloe.luau
-- GENERATED by tools/gen_rimefang_floe.py from assets/rimefang_floe.json - do
-- not hand-edit. `assets/arena_gen.py` writes that json as it builds the floe.
--
-- THE FLOOR OF RIMEFANG'S LAIR, AS %d SEPARATE OBJECTS. The fight sinks and
-- refreezes the ice it is played on and a Roblox mesh cannot change at
-- runtime, so the Floe v3 walkable disc is not one part: it is a seeded
-- Voronoi fracture of the disc r 0..%.0f into shards the server toggles one at
-- a time. Each is an imported MeshPart named `RimefangArena_ShardNN`, with its
-- ORIGIN AT ITS OWN CENTROID at floe-top height - so sinking one is a tween
-- down its own axis and not an offset from the arena centre.
--
-- WHAT THE NUMBERS ARE. `centre` is the shard's area centroid in ARENA-LOCAL
-- Roblox space (X and Z off the arena centre, Y the authored top height) -
-- the same convention `BossArenas.ice.thinIce` uses, so add `arena.center` to
-- get world. `ring` is measured off the finished outline, not assumed from a
-- seed: 0 touches the breathing hole in the middle, 3 touches the pressure
-- ridge, 1 and 2 are hops out across the neighbour graph. `neighbours` is the
-- shared-edge graph, which is what a spreading collapse walks. `area` is in
-- square studs, and it is the honest weight for "how much floor did that
-- cost" - the shards are deliberately unequal (%.0f to %.0f), because equal
-- ones read as tiles.
--
-- `hole` is the pre-cut opening at the centre: no shard covers it, `radius`
-- is the closest any shard edge comes to the middle, and the polygon edge
-- wanders OUT from there rather than in.
--
-- `thinIce` is the four shards the young-ice patches sit on. They ARE those
-- patches now - `BossArenas.ice.thinIce` used to carry four measured hub
-- positions and the server matched them against the mesh, which is a lookup
-- that can quietly find the wrong shard; these are ids.
--
-- The outlines themselves are NOT here. They are in the json, they are 3.5k
-- vertices, and nothing on the server needs them: a point-in-shard test is a
-- raycast at the real geometry, which is more accurate than a polygon copy
-- and cannot go stale.

local RimefangFloe = {}

-- The object name the arena mesh carries, per shard id.
RimefangFloe.OBJECT = "%s"

-- The breathing hole at the centre: pre-cut, covered by no shard.
RimefangFloe.hole = {
\tcentre = Vector3.new(0, %.2f, 0),
\tradius = %.2f,
}

-- The four shards that are the young ice.
RimefangFloe.thinIce = { %s }

export type Shard = {
\tcentre: Vector3,
\tring: number,
\tarea: number,
\tneighbours: { number },
}

-- A field assignment cannot carry a type annotation in Luau, so the table is
-- built as a typed local and hung on the module below it.
local shards: { [number]: Shard } = {
'''

FOOTER = """}

RimefangFloe.shards = shards

-- How many shards the floe has. Read this rather than counting the table:
-- `#` on a map-shaped table is not defined.
RimefangFloe.count = %d

-- Every shard in a ring, in id order. The fight's phase openers work a ring at
-- a time (the ring next to the hole goes first), so this is the shape the
-- collapse is actually written in.
function RimefangFloe.ring(index: number): { number }
\tlocal out = {}
\tfor id = 1, RimefangFloe.count do
\t\tlocal shard = RimefangFloe.shards[id]
\t\tif shard and shard.ring == index then
\t\t\ttable.insert(out, id)
\t\tend
\tend
\treturn out
end

-- The object name for a shard id, for a `FindFirstChild` on the placed arena.
function RimefangFloe.objectName(id: number): string
\treturn string.format(RimefangFloe.OBJECT, id)
end

return RimefangFloe
"""


def render(data):
    shards = data["shards"]
    areas = [shard["area"] for shard in shards]
    text = HEADER % (
        len(shards),
        data["floorRadius"],
        min(areas),
        max(areas),
        data["object"],
        data["top"],
        data["hole"]["radius"],
        ", ".join(str(id) for id in sorted(data["thinIce"])),
    )
    for shard in sorted(shards, key=lambda s: s["id"]):
        x, y, z = shard["centre"]
        text += "\t[%d] = {\n" % shard["id"]
        text += "\t\tcentre = Vector3.new(%.2f, %.2f, %.2f),\n" % (x, y, z)
        text += "\t\tring = %d,\n" % shard["ring"]
        text += "\t\tarea = %.1f,\n" % shard["area"]
        text += "\t\tneighbours = { %s },\n" % ", ".join(str(n) for n in shard["neighbours"])
        text += "\t},\n"
    return text + FOOTER % len(shards)


def main():
    check_only = "--check" in sys.argv[1:]
    if not os.path.exists(SOURCE):
        print("MISSING: %s - re-export the arena:" % SOURCE)
        print("  blender -b -P assets/arena_gen.py -- assets/arena_rimefang.glb rimefang preview")
        sys.exit(1)
    rendered = render(json.load(open(SOURCE)))
    current = open(OUT).read() if os.path.exists(OUT) else None

    if check_only:
        # Compare against the STYLUA'D form, because that is what is on disk:
        # a check that compared raw output would fail on every formatted file
        # and teach everyone to ignore it.
        formatted = stylua(rendered)
        state = "up to date" if current == formatted else "STALE"
        print("RimefangFloe.luau: %s (%d shards in %s)" % (state, len(json.load(open(SOURCE))["shards"]), os.path.relpath(SOURCE, ROOT)))
        if current != formatted:
            print("  re-run `python3 tools/gen_rimefang_floe.py` - the Luau table and the floe map disagree.")
            print("  (if the arena was re-exported, the shard NUMBERING may have moved: check the fight's")
            print("   own shard references too, not just this file.)")
            sys.exit(1)
        return

    with open(OUT, "w") as handle:
        handle.write(rendered)
    if os.path.exists(STYLUA):
        subprocess.run([STYLUA, OUT], check=True)
    print("WROTE: %s (%d shards)" % (os.path.relpath(OUT, ROOT), len(json.load(open(SOURCE))["shards"])))


def stylua(text):
    """`text` as stylua would leave it, without touching the real file."""
    if not os.path.exists(STYLUA):
        return text
    done = subprocess.run([STYLUA, "-"], input=text, capture_output=True, text=True)
    return done.stdout if done.returncode == 0 else text


if __name__ == "__main__":
    main()
