#!/usr/bin/env python3
"""Regenerate `src/Shared/Config/ArmorPalette.luau` from `assets/armor_palette.py`.

WHY THIS EXISTS. The armor redesign gives every mesh object in the ArmorPack a
ROLE (Under / Plate / Trim / Accent / Glow), and the role supplies both the
object's colour and its `Enum.Material`. That table has to be readable by two
languages: Blender (for the mannequin preview render) and Luau (for the worn
model). Hand-typing it twice is the exact failure `tools/gen_mesh_colors.py`'s
header documents - a parallel lane maintained half a table by hand and left 33
rows out, and every gate passed, because nothing in stylua/selene/rojo/
check_content knows that a name in a Python file needs a matching Luau row.

So `assets/armor_palette.py` is the ONE source and this writes the Luau.

UNLIKE `gen_mesh_colors.py` THIS NEEDS NO BLENDER. It is a plain import of a
pure-Python module - it runs in milliseconds, which means it can be run on
every edit, which is the whole point.

USAGE - after ANY edit to assets/armor_palette.py:

    python3 tools/gen_armor_palette.py            # regenerate the module
    python3 tools/gen_armor_palette.py --check    # report only, write nothing
                                                  # (exit 1 if stale)

`--check` is the gate-shaped form: CI or a pre-commit run can prove the
checked-in Luau matches the Python without rewriting the tree as a side
effect.

REGISTER LIMIT. The emitted module keeps exactly ONE top-level local
(`local ArmorPalette = {}`), the `Armor.luau` shape. The 200-local-per-chunk
Luau cliff took this game down on 2026-09-06 and is invisible to four of the
five gates; `python3 tools/check_compile.py` is the one that sees it.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "assets"))

import armor_palette  # noqa: E402  (needs the sys.path line above)

OUT = os.path.join(ROOT, "src", "Shared", "Config", "ArmorPalette.luau")

HEADER = [
    "--!strict",
    "-- ArmorPalette.luau",
    "-- GENERATED by tools/gen_armor_palette.py from assets/armor_palette.py",
    "-- - do not hand-edit. Edit the Python and re-run the generator.",
    "--",
    "-- Per-SET, per-ROLE colour + surface material for worn armor. The",
    "-- ArmorPack's object names carry four fields,",
    "--",
    "--     <Prefix>_<Slot>_<Target>_<Role>[<n>]",
    "--",
    "-- (e.g. `Cindershell_Chest_LeftUpperArm_Plate`), so a clone's own name",
    "-- says which row repaints it - the same idea WeaponModel's",
    "-- MESH_COLOR_KEY already ships. ArmorModel splits the name, strips any",
    "-- trailing digit off the role, and looks the role up here.",
    "--",
    "-- Studio's glTF importer does not carry colour OR material across (every",
    "-- imported part arrives default-grey Plastic), and there is no uploaded-PBR",
    "-- pipeline in this game - SurfaceAppearance is stripped on equip, repo-wide",
    "-- convention. Colour + `Enum.Material` is therefore the ENTIRE surface",
    "-- budget for armor, which is why the material is a first-class field here",
    "-- and not an afterthought: ten sets used to share one surface (Plastic),",
    "-- because ArmorService never set `Material` at all.",
    "--",
    "-- THE FIVE ROLES",
    "--   Under   the under-suit; the coverage layer. A target that receives an",
    "--           Under also gets its body part hidden at equip - that is what",
    "--           makes a set read as a worn SUIT instead of strapped-on plates.",
    "--   Plate   the hard armour; the primary silhouette read.",
    "--   Trim    cords, straps, buckles, rivets, fur edging.",
    "--   Accent  the one secondary luxury material (inlay, cape, ribbon).",
    "--   Glow    luminous sources only, where the MATERIAL is luminous (Neon).",
    "--",
    "-- Accent falls back to Plate and Glow falls back to Accent, so a",
    "-- half-authored set still looks deliberate rather than grey (the",
    "-- WeaponModel.colorMeshParts idiom). `ArmorPalette.role()` does that walk;",
    "-- callers should use it rather than indexing `items` directly.",
    "--",
    "-- Every colour is DERIVED, never invented: each is either a",
    "-- `Materials.items[*].color` (the material the piece is crafted from) or a",
    "-- `WorldService.MESH_COLOR` row (the island it comes from). The Python",
    "-- source carries the citation for every single row.",
    "--",
    "-- `hidesFace` marks the three sets that are full masks BY DESIGN. Only",
    "-- those three may hide the Head; everything else keeps the face open,",
    "-- because a faceless avatar is a bug report, not a look.",
]


def render():
    p = armor_palette
    lines = list(HEADER)
    lines += [
        "",
        "local ArmorPalette = {}",
        "",
        "export type Row = {",
        "\tcolor: Color3,",
        "\tmaterial: Enum.Material,",
        "\ttransparency: number,",
        "\tneon: boolean,",
        "}",
        "",
        "-- role -> the role it falls back to when a set omits it.",
        "ArmorPalette.FALLBACK = {",
    ]
    for role in sorted(p.ROLE_FALLBACK):
        lines.append('\t%s = "%s",' % (role, p.ROLE_FALLBACK[role]))
    lines += [
        "}",
        "",
        "-- The five role names, in layering order (outermost last).",
        "ArmorPalette.ROLES = { "
        + ", ".join('"%s"' % r for r in p.ROLES)
        + " }",
        "",
        "-- Authored standoff off the target part's surface, in studs. The",
        "-- generator's check_fit() enforces these at build time; they are",
        "-- published here so a reader of the runtime can see the budget.",
        "ArmorPalette.STANDOFF = {",
    ]
    for role in p.ROLES:
        if role in p.STANDOFF:
            lines.append("\t%s = %.2f," % (role, p.STANDOFF[role]))
    lines += [
        "}",
        "ArmorPalette.MAX_STANDOFF = %.2f" % p.MAX_STANDOFF,
        "",
        "-- Sets whose Under closes over the face by design (a full mask). These",
        "-- three and only these three may hide the Head.",
        "ArmorPalette.hidesFace = {",
    ]
    for prefix in sorted(p.HIDES_FACE):
        lines.append("\t%s = true," % prefix)
    lines += [
        "}",
        "",
        "-- Target -> the size the pack's objects for that target are AUTHORED",
        "-- against, in Roblox axes (the Python table is Blender's (x, y, z);",
        "-- the last two swap here, once, so nobody has to remember it).",
        "--",
        "-- This is what makes a provisional number cost fit precision and",
        "-- nothing worse: at equip ArmorModel compares the rig's real",
        "-- `character[Target].Size` against the row below and scales the",
        "-- sub-part - and its offset from the joint - by actual/authored. A",
        "-- wrong authored size therefore renders slightly wrong proportions",
        "-- rather than armour clipping through a limb or floating off it.",
        "--",
        "-- >> The six LIMB rows are PROVISIONAL << - Roblox's documented",
        "-- default R15 block-rig sizes, not values this repo has measured.",
        "-- Head / UpperTorso / the 2.0 hip width are the generator's own",
        "-- shipped constants and are trusted. See assets/armor_palette.py for",
        "-- the Studio probe that settles the rest.",
        "ArmorPalette.FIT = {",
    ]
    for target in sorted(p.FIT):
        x, y, z = p.FIT[target]["size"]
        lines.append(
            "\t%s = Vector3.new(%.2f, %.2f, %.2f)," % (target, x, z, y)
        )
    lines += [
        "}",
        "",
        "-- Equip slot -> the R15 parts that slot's objects dress. The pack's",
        "-- object names already carry their own target, so this is the",
        "-- published region map rather than a lookup the runtime needs; the",
        "-- generator's check_coverage() enforces the same table at build time.",
        "ArmorPalette.SLOT_TARGETS = {",
    ]
    for slot in ("Helm", "Chest", "Legs"):
        members = ", ".join('"%s"' % t for t in p.SLOT_TARGETS[slot])
        lines.append("\t%s = { %s }," % (slot, members))
    lines += [
        "}",
        "",
        "-- <modelPrefix> -> <Role> -> Row. Keys are the set's `modelPrefix`",
        "-- from Armor.sets, which is also the first field of every pack object's",
        "-- name.",
        "ArmorPalette.items = {",
    ]
    for prefix in sorted(p.PALETTES):
        lines.append("\t%s = {" % prefix)
        for role in p.ROLES:
            block = p.PALETTES[prefix]
            if role not in block:
                continue
            row = block[role]
            r, g, b = row["rgb"]
            lines.append("\t\t%s = {" % role)
            lines.append(
                "\t\t\tcolor = Color3.fromRGB(%d, %d, %d), -- %s"
                % (r, g, b, row["cite"])
            )
            lines.append("\t\t\tmaterial = Enum.Material.%s," % row["material"])
            lines.append("\t\t\ttransparency = %.2f," % row["transparency"])
            lines.append("\t\t\tneon = %s," % ("true" if row["neon"] else "false"))
            lines.append("\t\t},")
        lines.append("\t},")
    lines += [
        "}",
        "",
        "-- The row for a set prefix + role, walking the Accent -> Plate and",
        "-- Glow -> Accent fallbacks. nil when the set has no such role at all",
        "-- (or the prefix is unknown) - the caller then paints the piece's own",
        "-- row colour, so an unauthored object is never invisible.",
        "function ArmorPalette.role(prefix: string, role: string): Row?",
        "\tlocal block = ArmorPalette.items[prefix]",
        "\tif not block then",
        "\t\treturn nil",
        "\tend",
        "\tlocal seen = {}",
        "\tlocal name: string? = role",
        "\twhile name and not seen[name] do",
        "\t\tlocal found = block[name]",
        "\t\tif found then",
        "\t\t\treturn found",
        "\t\tend",
        "\t\tseen[name] = true",
        "\t\tname = ArmorPalette.FALLBACK[name]",
        "\tend",
        "\treturn nil",
        "end",
        "",
        "return ArmorPalette",
        "",
    ]
    return "\n".join(lines)


def main():
    check_only = "--check" in sys.argv[1:]
    rendered = render()
    sets = len(armor_palette.PALETTES)
    rows = sum(len(b) for b in armor_palette.PALETTES.values())
    rel = os.path.relpath(OUT, ROOT)
    if check_only:
        try:
            with open(OUT) as handle:
                current = handle.read()
        except IOError:
            current = None
        state = "up to date" if current == rendered else "STALE - re-run without --check"
        print("%s - %d sets, %d rows, %s" % (rel, sets, rows, state))
        if current != rendered:
            raise SystemExit(1)
        return
    with open(OUT, "w") as handle:
        handle.write(rendered)
    print("wrote %s - %d sets, %d rows" % (rel, sets, rows))


if __name__ == "__main__":
    main()
